version: '3.8'

services:
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ../apps/web:/app
      - /app/node_modules

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/tempotrackers
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ../apps/api:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tempotrackers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ml-pipeline:
    build:
      context: ../services/ml-pipeline
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/tempotrackers
    depends_on:
      - db
    volumes:
      - ../services/ml-pipeline:/app

volumes:
  postgres_data:
  redis_data:
