[project]
name = "tempotrackers-api"
version = "0.1.0"
description = "TempoTrackers API"
requires-python = ">=3.11,<3.12"

[build-system]
requires = ["setuptools>=45", "wheel", "pip>=21.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []